### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by iamkaram** [XifengGuo/DEC-keras#1]
Getting the error with the following message
run DEC.py mnist
Using TensorFlow backend.
Namespace(ae_weights=None, batch_size=256, dataset='mnist', gamma=0.1, maxiter=20000.0, n_clusters=10, save_dir='results', tol=0.001, update_interval=140)
MNIST samples (70000, 784)
No pretrained ae_weights given, start pretraining...
Pretraining the 1th layer...
learning rate = 0.1
Traceback (most recent call last):

  File "C:\Projects\ProvidersSimilarity\code\DEC-2\DEC-keras-master\DEC.py", line 311, in <module>
    x=x)

  File "C:\Projects\ProvidersSimilarity\code\DEC-2\DEC-keras-master\DEC.py", line 170, in initialize_model
    sae.fit(x, epochs=400)

  File "C:\Projects\ProvidersSimilarity\code\DEC-2\DEC-keras-master\SAE.py", line 133, in fit
    self.pretrain_stacks(x, epochs=epochs/2)

  File "C:\Projects\ProvidersSimilarity\code\DEC-2\DEC-keras-master\SAE.py", line 102, in pretrain_stacks
    self.stacks[i].fit(features, features, batch_size=self.batch_size, epochs=epochs/3)

  File "C:\Users\kaneja\AppData\Local\Continuum\Anaconda3\lib\site-packages\keras\models.py", line 867, in fit
    initial_epoch=initial_epoch)

  File "C:\Users\kaneja\AppData\Local\Continuum\Anaconda3\lib\site-packages\keras\engine\training.py", line 1598, in fit
    validation_steps=validation_steps)

  File "C:\Users\kaneja\AppData\Local\Continuum\Anaconda3\lib\site-packages\keras\engine\training.py", line 1130, in _fit_loop
    for epoch in range(initial_epoch, epochs):

TypeError: 'float' object cannot be interpreted as an integer

**Comment by XifengGuo** [comment]
@iamkaram It's because of python 3. The newest code is adapted to python3.
